jwt:
  signing_key: f11a18af934b4b758de6f7e9e7c239ac
  expiration_time: 72h
  buffer_time: 24h
  issuer: server

mysql:
  host: 192.168.80.130
  port: "3306"
  db_name: test
  username: root
  password: root
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 10s

system:
  ip: 0.0.0.0
  port: "8080"
  db_type: mysql
  config_path: ./config/config.yaml
  router_prefix: /api/v1
zap:
  level: info
  format: console
  director: log
  encode_level: LowercaseColorLevelEncoder
  log_in_console: true
